disabled_rules:
  - trailing_whitespace
  - shorthand_operator
  - syntactic_sugar
  - force_cast
  - force_try
  - force_unwrapping

line_length:
  ignores_comments: true
  warning: 100
  error: 120
  
function_body_length:
  warning: 150
  error: 300
  
file_length:
  warning: 500
  error: 1000
  
vertical_whitespace:
  max_empty_lines: 3
  
large_tuple:
  warning: 3
  
identifier_name:
  min_length:
    warning: 1

type_name:
  min_length:
    warning: 3
  max_length:
    warning: 40
    error: 60
  allowed_symbols: "_"

reporter: "xcode"
